# Import environment with:
# conda env create -f environment.yml
# conda env update --prefix ./env --file environment.yml --prune

name: datascience
channels:
  - conda-forge
  - default

dependencies:
  - jupyter
  - ipykernel
  - matplotlib
  - numpy=1.23.5
  - pandas
  - scikit-learn
  - seaborn
  - geopandas
  - shapely=1.8.5
  - python-graphviz