# Import environment with:
# conda env create -f environment.yml
# conda env update --prefix ./env --file environment.yml --prune

name: datascience
dependencies:
  - ipykernel
  - python
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - geopandas
  - xgboost
  - plotly
  - hyperopt
  - folium
  - python-kaleido
  - pip
  - pip:
    - git+https://github.com/hyperopt/hyperopt-sklearn


  